name: Test TF Action

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  # Test valid Terraform configurations (happy path)
  test-valid-configs:
    name: Test Valid Configurations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-case:
          - name: "Basic validation"
            workdir: "test/valid"
            env: "basic"

          - name: "With tfvar file"
            workdir: "test/valid"
            tfvar-files: "test.tfvars"
            env: "tfvar-file"

          - name: "With inline tfvars (comma-separated)"
            workdir: "test/valid"
            tfvars: "env=test,region=us-east-1"
            env: "comma-seperated-inline-tfvars"

          - name: "With inline tfvars (space-separated)"
            workdir: "test/valid"
            tfvars: "env=staging region=us-west-2"
            env: "space-seperated-inline-tfvars"

          - name: "With multiline tfvars"
            workdir: "test/valid"
            tfvars: |
              env=staging
              region=eu-west-1
            env: "multiline-tfvars"

          - name: "With inline backend config"
            workdir: "test/valid"
            backend-config-vars: "path=custom.tfstate"
            env: "backend-config-vars"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test TF Action - ${{ matrix.test-case.name }}
        id: tf-action-valid-test
        uses: ./
        with:
          workdir: ${{ matrix.test-case.workdir }}
          tfvar-files: ${{ matrix.test-case.tfvar-files }}
          tfvars: ${{ matrix.test-case.tfvars }}
          backend-config-vars: ${{ matrix.test-case.backend-config-vars }}
          env: ${{ matrix.test-case.env }}
          steps: validate,plan,apply

      - name: Verify action succeeded
        run: |
          if [ "${{ steps.tf-action-valid-test.outcome }}" != "success" ]; then
            echo "❌ Test failed: ${{ matrix.test-case.name }}"
            exit 1
          else
            echo "✅ Test passed: ${{ matrix.test-case.name }}"
          fi

  # Test invalid Terraform configurations (failure scenarios)
  test-invalid-configs:
    name: Test Invalid Configurations
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-case:
          - name: "Invalid syntax"
            workdir: "test/invalid"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test TF Action - ${{ matrix.test-case.name }}
        id: tf-action-invalid-test
        continue-on-error: true
        uses: ./
        with:
          workdir: ${{ matrix.test-case.workdir }}
          steps: validate

      - name: Verify action failed as expected
        run: |
          if [ "${{ steps.test-tf-action-invalid-test.outcome }}" == "success" ]; then
            echo "❌ Test failed: Expected failure but action succeeded for ${{ matrix.test-case.name }}"
            exit 1
          else
            echo "✅ Test passed: Action correctly failed for ${{ matrix.test-case.name }}"
          fi
